import * as fs from 'fs';
import * as path from 'path';
import type { ProjectAnalysis } from './project-analyzer';

const GENERATED_MARKER = '<!-- Generated by oh-my-copilot init -->';

export interface GeneratedAgentsFile {
  path: string;
  status: 'created' | 'updated' | 'kept';
}

function normalizeLanguages(analysis: ProjectAnalysis): string {
  return analysis.languages.join(', ') || 'Unknown';
}

function choosePackageManagers(analysis: ProjectAnalysis): string {
  return analysis.packageManagers.join(', ') || 'Unknown';
}

function buildRootContent(cwd: string, analysis: ProjectAnalysis): string {
  const projectName = path.basename(cwd);
  const sections = [
    GENERATED_MARKER,
    '# Working Context',
    '',
    `Repository: \`${projectName}\``,
    `Type: ${analysis.likelyAppType}`,
    `Languages: ${normalizeLanguages(analysis)}`,
    `Package managers: ${choosePackageManagers(analysis)}`,
    '',
    '## Structure',
    '- `src/`: CLI and Ink TUI package',
    '- `bridge/`: VS Code extension and local Copilot bridge server',
    '- `docs/`: user-facing documentation and localized READMEs',
    '- `scripts/`: installation and packaging helpers',
    '',
    '## Verification',
    '- `npm --prefix src run typecheck`',
    '- `npm --prefix src run build`',
    '- `npm --prefix src test`',
    '- `npm --prefix bridge run compile`',
    '',
    '## Editing Rules',
    '- Prefer surgical edits inside the package you are changing.',
    '- Do not manually edit generated build output under `dist/`.',
    '- Update package-level docs or install scripts when user-facing behavior changes.',
  ];

  return sections.join('\n') + '\n';
}

function buildDirectoryContent(relativeDir: string): string {
  const templates: Record<string, string[]> = {
    'src': [
      'Scope: top-level CLI package.',
      'Run package-local commands from this directory when verifying source changes.',
      'Keep `bin/` and `dist/` aligned with CLI entrypoint changes; avoid manual edits in `dist/`.',
    ],
    'src/src': [
      'Scope: main TypeScript source for the CLI, TUI, runtime, and tools.',
      'Prefer small domain modules over broad cross-cutting edits.',
      'If behavior changes user-visible flows, update the corresponding CLI/TUI command path too.',
    ],
    'src/src/ui': [
      'Scope: Ink UI components, hooks, and interaction flows.',
      'Keep TUI state transitions explicit and avoid mixing raw console output into Ink rendering.',
      'When changing render-stability-sensitive props, update `src/test/ui-render-stability.test.ts` if needed.',
    ],
    'src/src/cli': [
      'Scope: Commander commands and non-interactive CLI flows.',
      'Subcommands should finish cleanly and must not fall through into TUI startup.',
      'Keep stdout concise for CLI commands and reserve rich interaction for `chat` mode.',
    ],
    'src/src/provider': [
      'Scope: Copilot bridge provider and editor tool integration.',
      'Keep request/response formats compatible with the bridge server.',
      'Be careful with auth tokens, SSE streaming semantics, and model selection behavior.',
    ],
    'src/src/agent-runtime': [
      'Scope: autonomous execution loop, tool iteration, and verification flow.',
      'Protect completion semantics and avoid regressions in cancellation/timeout handling.',
      'Read-before-write and verification discipline should stay encoded here, not only in prompts.',
    ],
    'src/src/harness': [
      'Scope: project-specific harness team generation and activation.',
      'Preserve user-authored files; generated cleanup should only remove owned harness artifacts.',
      'If generation behavior changes, keep TUI progress and fallback messaging in sync.',
    ],
    'src/test': [
      'Scope: Bun tests for the CLI package.',
      'Prefer focused regression tests around UI rendering, command flow, and runtime helpers.',
    ],
    'bridge': [
      'Scope: VS Code extension package and packaged VSIX artifact.',
      'Compile after changes and avoid unnecessary UX that exposes bridge internals or tokens.',
      'Do not edit generated files in `dist/` manually.',
    ],
    'bridge/src': [
      'Scope: extension activation, bridge server, and bridge metadata.',
      'Keep local-only security assumptions intact: loopback binding, bearer auth, no unnecessary token exposure.',
      'Maintain compatibility between HTTP bridge endpoints and the CLI provider client.',
    ],
    'docs': [
      'Scope: documentation, release notes, and localized READMEs.',
      'Keep command names and behavior descriptions aligned with the current CLI.',
      'When changing key UX, update Korean/Chinese docs if the change is user-facing.',
    ],
    'scripts': [
      'Scope: install and setup helpers.',
      'Avoid hardcoded version numbers or repo-relative path mistakes.',
      'Installer scripts should degrade gracefully when optional tooling is missing.',
    ],
  };

  const body = templates[relativeDir] ?? [
    `Scope: \`${relativeDir}\`.`,
    'Keep edits local to this directory and preserve the repository conventions inherited from parent `AGENTS.md` files.',
  ];

  return [
    GENERATED_MARKER,
    '# Directory Context',
    '',
    ...body.map(line => `- ${line}`),
    '',
  ].join('\n');
}

function writeGeneratedFile(filePath: string, content: string, force = false): GeneratedAgentsFile {
  if (!fs.existsSync(filePath)) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, 'utf8');
    return { path: filePath, status: 'created' };
  }

  const existing = fs.readFileSync(filePath, 'utf8');
  const isGenerated = existing.includes(GENERATED_MARKER);
  if (!isGenerated && !force) {
    return { path: filePath, status: 'kept' };
  }

  if (existing === content) {
    return { path: filePath, status: 'kept' };
  }

  if (isGenerated && force) {
    fs.writeFileSync(filePath, content, 'utf8');
    return { path: filePath, status: 'updated' };
  }

  if (isGenerated && existing !== content) {
    fs.writeFileSync(filePath, content, 'utf8');
    return { path: filePath, status: 'updated' };
  }

  return { path: filePath, status: 'kept' };
}

function getCandidateDirectories(cwd: string): string[] {
  const candidates = [
    '',
    'src',
    'src/src',
    'src/src/ui',
    'src/src/cli',
    'src/src/provider',
    'src/src/agent-runtime',
    'src/src/harness',
    'src/test',
    'bridge',
    'bridge/src',
    'docs',
    'scripts',
  ];

  return candidates
    .map(relative => path.join(cwd, relative))
    .filter(dir => fs.existsSync(dir) && fs.statSync(dir).isDirectory());
}

export function generateHierarchicalAgents(
  cwd: string,
  analysis: ProjectAnalysis,
  force = false,
): GeneratedAgentsFile[] {
  const results: GeneratedAgentsFile[] = [];

  for (const dirPath of getCandidateDirectories(cwd)) {
    const relativeDir = path.relative(cwd, dirPath);
    const content = relativeDir === ''
      ? buildRootContent(cwd, analysis)
      : buildDirectoryContent(relativeDir);
    results.push(writeGeneratedFile(path.join(dirPath, 'AGENTS.md'), content, force));
  }

  return results;
}
