#!/usr/bin/env node
import { build } from 'esbuild';
import { readFileSync } from 'fs';

const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));

// Deps that have native addons or must not be bundled
const external = [
  // Native MCP stdio transport uses child_process internally — keep external
];

await build({
  entryPoints: ['src/main.tsx'],
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'esm',            // ink v6 requires ESM (top-level await)
  outfile: 'dist/bundle.mjs',
  jsx: 'automatic',
  jsxImportSource: 'react',
  sourcemap: 'inline',
  logLevel: 'warning',
  minify: false,
  // All node_modules stay external — resolved natively at runtime.
  // This avoids dynamic-require bundling issues and keeps the bundle small.
  packages: 'external',
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  banner: {
    // Inject CJS shims so that require() calls in bundled deps work in ESM context
    js: [
      '// oh-my-copilot bundle — generated by esbuild',
      "import { createRequire } from 'module';",
      "import { fileURLToPath } from 'url';",
      "import { dirname } from 'path';",
      'const require = createRequire(import.meta.url);',
      'const __filename = fileURLToPath(import.meta.url);',
      'const __dirname = dirname(__filename);',
    ].join('\n'),
  },
}).catch((err) => {
  console.error('Build failed:', err.message);
  process.exit(1);
});

console.log('✓ Built dist/bundle.mjs');
